### ISSUE TITLE
About pre-trained model

### ISSUE THREAD

**Issue by midsommar-2019** [Nauhcnay/flatting#1]
I found the flat magic paper interesting and will be glad if i can test it. 
However when I tried to download the pre-trained model, Google drive said there isn't the requested file.
If you don't mind would you share the pre-trained model again?

Thank you

**Comment by Nauhcnay** [comment]
Hi,
Yes, I will update my whole readme file and clean up my code recently,
including the pre-trained model as well. I will let you know in this thread
when I'm ready.

**Comment by Nauhcnay** [comment]
The plugin file and pertained model have been updated, all the download links are available now.
